.vscode/settings.json, Backend/observator/.gitattributes, Backend/observator/.gitignore, Backend/observator/.mvn/wrapper/maven-wrapper.properties, Backend/observator/mvnw, Backend/observator/mvnw.cmd, Backend/observator/pom.xml, Backend/observator/src/main/java/com/happy/observator/ObservatorApplication.java, Backend/observator/src/main/java/com/happy/observator/config/PasswordEncoderConfig.java, Backend/observator/src/main/java/com/happy/observator/config/SecurityConfig.java, Backend/observator/src/main/java/com/happy/observator/model/HomeController.java, Backend/observator/src/main/java/com/happy/observator/model/LoginController.java, Backend/observator/src/main/java/com/happy/observator/model/User.java, Backend/observator/src/main/java/com/happy/observator/repository/UserRepositary.java, Backend/observator/src/main/java/com/happy/observator/service/UserService.java, Backend/observator/src/main/java/com/happy/observator/service/dummy.md, Backend/observator/src/main/resources/application.properties, Backend/observator/src/main/resources/templates/home.html, Backend/observator/src/main/resources/templates/login.html, Backend/observator/src/test/java/com/happy/observator/ObservatorApplicationTests.java, Frontend/dummy.md, ML/dummy.md
백앤드 생성
repo layer 생성
User DB 틀 생성
빈 폴더 생성을 위한 dummy.md 생성
=> Feat: initate backend and add repo layer

ML/eval_orderbooks/dummy.md, ML/eval_ticks/dummy.md, ML/orderbooks/dummy.md, ML/ticks/dummy.md
- Added a `dummy.md` file to allow Git to track an otherwise empty folder.
- Ensures that the folder is included in version control even when no files are present.
=> chore: Add dummy file to ensure empty folder is tracked

Backend/observator/pom.xml, Backend/observator/src/main/java/com/happy/observator/config/SecurityConfig.java, Backend/observator/src/main/java/com/happy/observator/model/ProfileController.java, Backend/observator/src/main/java/com/happy/observator/model/User.java, Backend/observator/src/main/java/com/happy/observator/service/UserService.java, Backend/observator/src/main/resources/templates/home.html, Backend/observator/src/main/resources/templates/profile.html, Frontend/dummy.md
* add profile page
* add site for Upbit key input
* delete dummy file
=> Feat: Add profile page

Backend/observator/src/main/java/com/happy/observator/model/User.java, Backend/observator/src/main/java/com/happy/observator/service/UserService.java, Backend/observator/src/main/resources/templates/login.html, Backend/observator/src/main/resources/templates/profile.html, Backend/observator/src/main/resources/templates/signup.html
* check if both upbit keys are input
* reconnect html and Backend
=> Feat: add upbitkey check feature

Backend/observator/pom.xml, Backend/observator/src/main/java/com/happy/observator/Upbit/UpbitApiUtil.java, Backend/observator/src/main/java/com/happy/observator/Upbit/UpbitBalance.java, Backend/observator/src/main/java/com/happy/observator/model/ProfileController.java, Backend/observator/src/main/java/com/happy/observator/model/User.java, Backend/observator/src/main/java/com/happy/observator/service/UpbitService.java, Backend/observator/src/main/resources/templates/profile.html, Frontend/node_modules/.package-lock.json, Frontend/package-lock.json, Frontend/package.json
* use access and secret keys to get balance information from Upbit
* only get information when keys are input so that it can avoid getting errors
=> Feat: Add Check balance feature

Backend/observator/pom.xml, Backend/observator/src/main/java/com/happy/observator/config/SecurityConfig.java, Backend/observator/src/main/java/com/happy/observator/model/SignupController.java, Backend/observator/src/main/java/com/happy/observator/model/User.java, Backend/observator/src/main/java/com/happy/observator/service/UserService.java, Backend/observator/src/main/resources/templates/signup.html
* Update Spring boot version from 3.3.4 to 3.3.5
* Fix signup error where frontend had wrong controller endpoint
* Disabled CSRF protection for H2 console connection
* Add logger for saveUser check
* Add new User Constructor for 4 inputs(username, password, email, phonenumber)
=> Fix: Fix signup error

Backend/observator/src/main/java/com/happy/observator/config/SecurityConfig.java, Backend/observator/src/main/java/com/happy/observator/model/SignupController.java
* Replace deprecated code
* Delete unused class import
=> Fix: Replace deprecated code

README.md
* Key codes for project on AWS EC2 Instance server
=> Docs: Add link for server codes

Backend/observator/src/main/java/com/happy/observator/model/TradeController.java, Backend/observator/src/main/java/com/happy/observator/service/UpbitService.java, Backend/observator/src/main/resources/templates/trade.html
* input Bitcoin volume and click 'Sell Bicoin' button to sell bitcoin
=> Feat: Add sell feature

Backend/observator/src/main/java/com/happy/observator/model/TradeController.java, Backend/observator/src/main/resources/templates/trade.html
* input buy/sell time to reserve an order at a designated time
=> Feat: add time setting

Backend/observator/src/main/java/com/happy/observator/ObservatorApplication.java, Backend/observator/src/main/resources/application.properties
* Add how to change comments based on database settings
* If using h2 database, use comment on My-SQL realated lines in application.properties
* If using My-SQL, use comment on h2 realated lines in application.properties
=> Fix: Add information about comments

Backend/observator/src/main/resources/Frontend/package-lock.json, Backend/observator/src/main/resources/Frontend/package.json, Backend/observator/src/main/resources/templates/trade.html
* fix trade.html trade error
* add method='post' to connect to backend
=> Fix: fix trade error

Backend/observator/pom.xml, Backend/observator/src/main/java/com/happy/observator/ObservatorApplication.java, Backend/observator/src/main/java/com/happy/observator/model/TradeController.java, Backend/observator/src/main/resources/application.properties, Backend/observator/src/main/resources/templates/trade.html
* changed the time format to hh:mm:ss.SSS to use milliseconds in scheduled trading
=> Feat: add millisecond in time

Backend/observator/src/main/java/com/happy/observator/ObservatorApplication.java, Backend/observator/src/main/java/com/happy/observator/model/OrderRequest.java, Backend/observator/src/main/java/com/happy/observator/model/TradingOrderProcessor.java, Backend/observator/src/main/java/com/happy/observator/repository/UserRepositary.java, Backend/observator/src/main/resources/application.properties, Backend/observator/src/main/resources/dummy_orders.json
* use json file to input order
=> Feat: use json file to input order

Backend/observator/src/main/java/com/happy/observator/ObservatorApplication.java, Backend/observator/src/main/java/com/happy/observator/model/TradeController.java, Backend/observator/src/main/resources/application.properties, Backend/observator/src/main/resources/templates/trade.html
* add framework for starting and ending auto-trade
* fix redirect problem in /trade
=> Feat: add framework for auto-trade

Backend/observator/src/main/java/com/happy/observator/model/ProfileController.java, Backend/observator/src/main/java/com/happy/observator/model/TradeController.java, Backend/observator/src/main/java/com/happy/observator/service/UserService.java, Backend/observator/src/main/resources/templates/css/profile.css, Backend/observator/src/main/resources/templates/profile.html, Backend/observator/src/main/resources/templates/trade.html
* add masking for secret key
* add email update
* make framework for starting and ending auto-trade
* change frontend of starting and ending auto-trade to get parameters
* add features to change risk levels
=> Feat: add auto-trade framework, secret key masking, email updates

Backend/observator/src/main/java/com/happy/observator/model/TradeController.java, Backend/observator/src/main/resources/templates/trade.html
* change risk level to Threshold level
* change level to float to match ML input
=> Feat: change risk level to Threshold level

Backend/observator/src/main/resources/templates/tem2/scripts.js, Backend/observator/src/main/resources/templates/tem2/styles-trade.css, Backend/observator/src/main/resources/templates/tem2/trade.html
This PR adds a dynamic table that fetches and displays the top 35 cryptocurrencies (excluding BTC) from Upbit API. It includes the following features:
- Displays coin name, current price, daily percentage change, and 24-hour trading volume.
- Updates data every second using JavaScript and Upbit's public API.
- Compact table design for better visibility in small spaces.
Please review and merge.
=> Add crypto price table for top 35 cryptocurrencies

Backend/observator/src/main/resources/static/assets/js/scripts.js, Backend/observator/src/main/resources/templates/trade.html
* add total value, profit/loss, and Asset Breakdown
* update every second
=> Feat: add asset info

Backend/observator/src/main/java/com/happy/observator/model/EmailController.java
* fix email service problem where the program could not get user info
=> Fix: email service

Backend/observator/src/main/java/com/happy/observator/model/TradeController.java, Backend/observator/src/main/java/com/happy/observator/model/TradingOrderProcessor.java
* add /order which have both /buy and /sell functions
* change TradingOrderProcessor scheduled order from to non-scheduled order
=> Feat: add non-scheduled order

Backend/observator/src/main/java/com/happy/observator/model/TradeController.java, Backend/observator/src/main/resources/static/assets/js/scripts.js, Backend/observator/src/main/resources/templates/login.html, Backend/observator/src/main/resources/templates/trade.html
* add a way to change threshold during auto-trade without stopping it
* change display based on whether auto-trade is on or not
* add error message for login errors
=> Feat: add threshold change and error message for login errors

Backend/observator/src/main/java/com/happy/observator/model/TradeController.java, Backend/observator/src/main/resources/static/assets/js/scripts.js, Backend/observator/src/main/resources/templates/trade.html
* change into AJAX
* send success/fail message
=> Fix: fix manual buy/sell

README.md
Minor Changes
- linked documents
- added emojis
=> Chore:Modify README.md
